import "./globals.css";

export const metadata = {
  title: "CPRG306-Assignments",
  description: "Generated by Amrit Reddy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
